language: java
jdk:
  - openjdk8

branches:
  only:
    - dev_1

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r about_me_server *
  - mkdir -p deploy
  - mv about_me_server.zip deploy/about_me_server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: aboutme-study-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ABOUT-ME-APP/about_me_server #Github 주소
      branch: dev_1


  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: aboutme-study-deploy # S3 버킷
    key: about_me_server.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: springboot-study # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-study-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: ABOUT-ME-APP/about_me_server
      branch: dev_1

notifications:
  email:
    recipients:
      - kwx4957@gmail.com
      - aboutme2auth@gmail.com